#!/bin/bash
export PATH=/root/x-tools/arm-plum-linux-gnueabi/bin:$PATH
export CROSS=arm-plum-linux-gnueabi
export CC=${CROSS}-gcc
export LD=${CROSS}-ld
export AS=${CROSS}-as
export AR=${CROSS}-ar

echo "Configuring and making libncurses"
cd /opt/arm/ncurses-5.9
./configure arm-linux --target=arm-linux --host=x86_64-linux-gnu --with-build-cc=gcc --prefix=/opt/arm --with-shared --without-debug --without-ada --enable-overwrite
make install

echo "Configuring and making libopenssl"
cd ../
cd /opt/arm/openssl-1.0.2d
./Configure -DOPENSSL_NO_HEARTBEATS --openssldir=/opt/arm no-shared os/compiler:arm-linux-gnueabi-gcc
make install

export CFLAGS='-Os '

echo "Configuring and making libsodium"
cd ../
cd /opt/arm/libsodium-1.0.3
./configure --host=arm-linux-gnueabi --prefix=/opt/arm
make install
